version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3131:3131"
    depends_on:
      - mongodb
    environment:
      - PORT=3131
      - MONGODB_URI=mongodb://mongodb:27717/promptLab
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27717:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
