name: 'promptlab'

services:
  promptlab:
    image: thefootonline/promptlab:latest  # Or use 0.9.0-beta for the specific version
    ports:
      - "3131:3131"  # Web UI available at http://localhost:3131
    depends_on:
      - mongodb
    environment:
      - PORT=3131
      - MONGODB_URI=mongodb://mongodb:27017/promptLab
      - NODE_ENV=production
      # ↓ Add your API keys here ↓
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27717:27017"  # Using custom port to avoid conflicts with existing MongoDB
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:  # Persistent volume for MongoDB data