name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'LICENCE'
      - '.gitignore'

jobs:
  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci-common.yml
    with:
      node-version: '22'
      run-dependency-check: true
      run-frontend-tests: true
      run-backend-tests: true
      run-lint: true
      run-build: true
      run-docker-build: true
